version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: circle_ruby_test
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ""
      - image: redis:3.2-alpine

    working_directory: ~/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-bundle-{{ checksum "Gemfile.lock" }}

      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-bundle-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rspec
